"""Regenerate src/main/resources/com/npcpermadeath/bosses.txt from the OSRS Wiki.

Pulls every page in Category:Bosses and writes one NPC name per line. Pages
that are not themselves an NPC (overview pages like "Barrows") are harmless:
no NPC carries that name. Disambiguation suffixes are stripped.

    python tools/generate_bosses.py
"""
import json
import re
import urllib.parse
import urllib.request
from pathlib import Path

API = "https://oldschool.runescape.wiki/api.php"
UA = "npc-permadeath build script (https://github.com/Dewdul)"
OUT = Path(__file__).resolve().parent.parent / "src/main/resources/com/npcpermadeath/bosses.txt"


def fetch_category(title):
    names, cont = [], {}
    while True:
        q = {"action": "query", "list": "categorymembers", "cmtitle": title,
             "cmlimit": "500", "cmnamespace": "0", "format": "json"}
        q.update(cont)
        req = urllib.request.Request(API + "?" + urllib.parse.urlencode(q), headers={"User-Agent": UA})
        data = json.load(urllib.request.urlopen(req))
        names += [m["title"] for m in data["query"]["categorymembers"]]
        if "continue" not in data:
            return names
        cont = data["continue"]


def main():
    names = set()
    for title in fetch_category("Category:Bosses"):
        title = re.sub(r"\s*\([^)]*\)$", "", title).strip()
        if title:
            names.add(title)
    lines = ["# Generated by tools/generate_bosses.py from the OSRS Wiki Category:Bosses",
             "# One NPC name per line, matched case-insensitively."]
    lines += sorted(names, key=str.lower)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(names)} names to {OUT}")


if __name__ == "__main__":
    main()
